version: "3"
services:
  postgres_ignite:
    container_name: postgres_ignite
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres_ignite

networks:
  postgres_ignite:
    driver: bridge
